version: '2'

services:
  react:
    image: mhart/alpine-node:8
    volumes:
      - ./react-frontend:/app
    ports:
      - "3030:3000"
    depends_on:
      - mongo
    command: sh -c "cd /app && yarn install && yarn start"
  mongo:
    image: mongo:3.5
    volumes:
      - ./mongodb_data:/data/db
  server:
    image: mhart/alpine-node:8
    volumes:
      - ./server:/app
    ports:
        - "3038:3000"
    depends_on:
      - mongo
    command: sh -c "cd /app && yarn install && yarn start "
